-- CreateTable
CREATE TABLE "Diet" (
    "IDT_DIET" TEXT NOT NULL,
    "NUM_QUANTITY" INTEGER,
    "DES_DESCRIPTION" TEXT,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DAT_UPDATED" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Diet_pkey" PRIMARY KEY ("IDT_DIET")
);

-- CreateIndex
CREATE UNIQUE INDEX "Diet_NUM_QUANTITY_key" ON "Diet"("NUM_QUANTITY");
