-- CreateTable
CREATE TABLE "Calories" (
    "IDT_CALORIES" TEXT NOT NULL,
    "NUM_QUANTITY" INTEGER NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Calories_pkey" PRIMARY KEY ("IDT_CALORIES")
);

-- CreateTable
CREATE TABLE "Diet" (
    "IDT_DIET" TEXT NOT NULL,
    "IDT_CALORIES" TEXT NOT NULL,
    "DES_DESCRIPTION" TEXT NOT NULL,
    "DAT_CREATED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Diet_pkey" PRIMARY KEY ("IDT_DIET")
);

-- CreateIndex
CREATE UNIQUE INDEX "Diet_IDT_CALORIES_key" ON "Diet"("IDT_CALORIES");

-- AddForeignKey
ALTER TABLE "Diet" ADD CONSTRAINT "Diet_IDT_CALORIES_fkey" FOREIGN KEY ("IDT_CALORIES") REFERENCES "Calories"("IDT_CALORIES") ON DELETE RESTRICT ON UPDATE CASCADE;
